In [2]:
import numpy as np

# Verify NumPy array creation
print("NumPy version:", np.__version__)

# Create and display a baseline Identity matrix 
R_identity = np.eye(3)
print("\nIdentity Rotation Matrix:")
print(R_identity)


NumPy version: 2.5.1

Identity Rotation Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
